//! The `x4c` backend: P4 compiled to Rust, adapted onto up4's contracts.

/// Code generated by x4c from `p4/programs/*/*.softnpu.p4`, committed so a
/// build needs neither the compiler nor network access to it.
///
/// Regenerate with `tools/p4/x4c.sh generate crates/up4-x4c/src/generated`;
/// CI regenerates and diffs, so a stale checkout fails rather than drifts.
pub mod generated {
    // Generated code is not held to up4's lint bar; it is held to producing
    // the same verdicts as every other backend on the conformance corpus.
    // Reformatting or hand-editing it to satisfy a lint would break the
    // regenerate-and-diff check, so the lints are silenced instead.
    #![allow(warnings, clippy::all, clippy::pedantic)]
    pub mod l2fwd;
    pub mod l3fwd;
}

#[cfg(test)]
mod tests {
    use crate::generated::l2fwd;
    use p4rs::{Pipeline, packet_in};

    /// The load-bearing question for this backend: does compiler output, built
    /// in up4's workspace, actually forward a frame? Everything else — the
    /// adapter, the journal, the corpus — is downstream of this being true.
    #[test]
    fn generated_l2fwd_forwards_to_the_port_its_table_names() {
        let mut p = l2fwd::main_pipeline::new(2);
        // Keys are wire order, action parameters little-endian (the ABI
        // up4-engine's `x4c` module pins with fixed vectors).
        p.add_table_entry(
            "ingress.mac_dst",
            "forward",
            &[0x02, 0, 0, 0, 0, 0x02],
            &[1, 0],
            0,
        );

        let frame = [
            0x02, 0, 0, 0, 0, 0x02, // dst: the entry above
            0x02, 0, 0, 0, 0, 0x01, // src
            0x08, 0x00, // ethertype
            0xde, 0xad, 0xbe, 0xef, // payload
        ];
        let mut pkt = packet_in::new(&frame);
        let out = p.process_packet(0, &mut pkt);

        assert_eq!(out.len(), 1, "one copy out");
        assert_eq!(out[0].1, 1, "forwarded to the port the table names");
    }

    /// A miss floods, which is the whole of l2fwd's learning-free behaviour.
    #[test]
    fn generated_l2fwd_broadcasts_an_unknown_destination() {
        let mut p = l2fwd::main_pipeline::new(4);
        let frame = [
            0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x02, 0, 0, 0, 0, 0x01, 0x08, 0x00, 0xde, 0xad,
        ];
        let mut pkt = packet_in::new(&frame);
        let out = p.process_packet(0, &mut pkt);
        assert!(
            out.len() > 1,
            "a miss replicates rather than forwarding to one port; got {}",
            out.len()
        );
    }
}
